# Generated by Django 5.2.4 on 2025-09-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='testcase_type',
            field=models.CharField(blank=True, default='functional', max_length=20, null=True),
        ),
    ]
