# Generated by Django 5.2.4 on 2025-09-01 06:47

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasemodel',
            name='testcase_type',
            field=models.CharField(blank=True, default='functionality', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('class_1', 'Class 1'), ('class_2', 'Class 2'), ('class_3', 'Class 3')], default='class_1', max_length=20)),
                ('output_counts', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Number of Cases')),
                ('testcase_type', models.CharField(blank=True, default='functionality', max_length=20, null=True)),
                ('modes', models.CharField(choices=[('classic', 'Classic'), ('ai', 'AI')], default='classic', max_length=20)),
                ('modules', models.ManyToManyField(blank=True, related_name='moduels', to='core.module')),
            ],
            options={
                'verbose_name': 'Test Plan',
                'verbose_name_plural': 'Test Plans',
            },
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('testscore', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('testcases', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='core.testcasemodel')),
                ('testplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.testplan')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testplan',
            name='testcases',
            field=models.ManyToManyField(blank=True, through='core.TestScore', to='core.testcasemodel'),
        ),
    ]
