# Generated by Django 5.2.7 on 2025-10-03 08:10

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_testplan_testcase_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="testplan",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name="HistoryTestPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("version", models.CharField(max_length=100, verbose_name="Version")),
                (
                    "other_changes",
                    models.JSONField(
                        blank=True,
                        help_text="Store other changes in JSON format",
                        null=True,
                    ),
                ),
                (
                    "testplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_plans",
                        to="core.testplan",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
