# Generated by Django 5.2.4 on 2025-09-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testcasemodel_testcase_type_testplan_testscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, related_name='moduels', to='core.module'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='testcases',
            field=models.ManyToManyField(blank=True, null=True, through='core.TestScore', to='core.testcasemodel'),
        ),
    ]
