# Generated by Django 5.2.7 on 2025-10-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_testplan_is_active_historytestplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="testscore",
            name="mode",
            field=models.CharField(
                choices=[("classic", "Classic"), ("ai", "AI")],
                default="ai",
                max_length=20,
            ),
        ),
    ]
