# Generated by Django 5.2.4 on 2025-09-11 09:41

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_testplan_modules_alter_testplan_testcases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=4, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='testplan',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, related_name='modules', to='core.module'),
        ),
    ]
