# Generated by Django 5.2.7 on 2025-10-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_testscore_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testscore",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[("classic", "Classic"), ("ai", "AI")],
                default="ai",
                max_length=20,
                null=True,
            ),
        ),
    ]
