# Generated by Django 5.2.7 on 2025-10-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_testscore_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rpnvalue",
            name="max_value",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="testplan",
            name="modes",
            field=models.CharField(
                choices=[("classic", "Classic"), ("ai", "AI"), ("manual", "Manual")],
                default="classic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="testscore",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[("classic", "Classic"), ("ai", "AI"), ("manual", "Manual")],
                default="ai",
                max_length=20,
                null=True,
            ),
        ),
    ]
