# Generated by Django 5.2.7 on 2025-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_rpnvalue_max_value_alter_testplan_modes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcasemodel",
            name="testcase_type",
            field=models.CharField(
                blank=True, default="functional", max_length=20, null=True
            ),
        ),
    ]
