# Generated by Django 5.2.4 on 2025-10-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_testcasemodel_testcase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='testscore',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
