# Generated by Django 5.2.4 on 2025-10-13 12:50

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_testcasemodel_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISessionStore',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.CreateModel(
            name='TestCaseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rpn_value', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('failure_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('code_change', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('defect_density', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('penality', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('testcases', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.testcasemodel')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestPlanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='Version')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('output_counts', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Cases')),
                ('testcase_data', models.JSONField(blank=True, null=True, verbose_name='Test Case Data')),
                ('status', models.CharField(blank=True, choices=[('saved', 'Saved'), ('draft', 'Draft')], default='draft', null=True)),
                ('modules', models.ManyToManyField(blank=True, null=True, related_name='generated_modules', to='core.module')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.aisessionstore')),
            ],
            options={
                'unique_together': {('session', 'version')},
            },
        ),
    ]
