# Generated by Django 5.2.4 on 2025-11-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aisessionstore_alter_project_name_testcasescore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscore',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
