# Generated by Django 5.2.4 on 2025-11-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_testscore_reasoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='testcases',
            field=models.ManyToManyField(blank=True, null=True, related_name='testscore', through='core.TestScore', to='core.testcasemodel'),
        ),
    ]
