# Generated by Django 5.2.4 on 2025-11-09 17:40

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_testplan_testcases'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rpn_value', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('failure_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('code_change', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('defect_density', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('penality', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('testcases', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.testcasemodel')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TestCaseScore',
        ),
    ]
