# Generated by Django 5.2.4 on 2025-11-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testcasescoremodel_delete_testcasescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplansession',
            name='version_info',
            field=models.TextField(blank=True, null=True, verbose_name='Version Info'),
        ),
    ]
